name: altme
description: AltMe Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.0
  google_fonts: ^2.3.1
  intl: ^0.17.0
  network:
    path: ./packages/network
  secure_storage:
    path: packages/secure_storage

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mockito: ^5.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/splash/
    - assets/icon/
