name: altme
description: AltMe Flutter App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10
  flutter_svg: ^1.0.0
  google_fonts: ^2.3.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  network_image_mock: ^2.1.0
  secure_storage:
    path: packages/secure_storage
  url_launcher: ^6.0.17
  uuid: ^3.0.5


dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2
  json_serializable: ^6.1.3
  mockingjay: ^0.3.0
  mockito: ^5.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/splash/
    - assets/icon/
    - assets/image/
    - assets/privacy/
