name: network
description: network package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.3.2
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0